name: Build
on: [push]

permissions:
  contents: read # for checkout

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel nml
      - name: Build
        #run: python build.py
        run: |
          nmlc --version
          npm i -D conventional-changelog-conventionalcommits
          npx conventional-changelog --help
          npx conventional-changelog -p conventionalcommits -r 0 -o build/changelog.md