name: Release
on:
  push:
    branches:
      - main
      - feature/*

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel nml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        # first run a dry run of the release to get the version number to be compiled into the grf
        run: |
          nmlc --version
          npm i conventional-changelog-conventionalcommits@9.0.0 conventional-changelog@7.0.2
          npx conventional-changelog -p conventionalcommits -r 0 -f -o changelog.md
          npx semantic-release --dry-run